name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Create assets directory
      run: mkdir -p android/app/src/main/assets
    
    - name: Bundle JavaScript
      run: |
        npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res
    
    - name: Build APK
      run: |
        cd android
        chmod +x gradlew
        ./gradlew assembleRelease --no-daemon
    
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: labobo-coloring-app
        path: android/app/build/outputs/apk/release/app-release.apk
        retention-days: 30
    
    - name: Upload build info
      uses: actions/upload-artifact@v3
      with:
        name: build-info
        path: |
          android/app/build/outputs/
          android/app/build/intermediates/
        retention-days: 7 